# .pre-commit-config.yaml

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Możemy to później zaktualizować komendą autoupdate
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        files: ^app/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0 # Możemy to później zaktualizować
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1 # Możemy to później zaktualizować
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML, sqlalchemy]
